sku_map = {
    "ICE CREAM FROCO VNLLA BN": "VANILLA BEAN",
    "ICE CREAM FROCO PNT BTTR": "PEANUT BUTTER",
    "ICE CREAM FROCO MOCHA JO": "MOCHA JOE",
    "ICE CREAM FROCO STRWBRY": "STRAWBERRY",
    "FROCO,VANILLA BEAN": "VANILLA BEAN",
    "FROCO,PEANUT BUTTER": "PEANUT BUTTER",
    "FROCO,MOCHA JOE": "MOCHA JOE",
    "FROCO,STRAWBERRY": "STRAWBERRY",
}